### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zyox123cc** [MoonlyDays/TF2_MinecraftBlocks#1]
L 04/23/2019 - 21:53:41: [SM] Call stack trace:
L 04/23/2019 - 21:53:41: [SM]   [0] GetClientEyeAngles
L 04/23/2019 - 21:53:41: [SM]   [1] Line 49, C:\Users\User\Desktop\scripts\minecraft.sp::Hook_EntitySound
L 04/23/2019 - 21:53:41: [SM] Exception reported: Invalid client index 536
L 04/23/2019 - 21:53:41: [SM] Blaming: minecraft.smx
L 04/23/2019 - 21:53:41: [SM] Call stack trace:
L 04/23/2019 - 21:53:41: [SM]   [0] GetClientEyeAngles
L 04/23/2019 - 21:53:41: [SM]   [1] Line 49, C:\Users\User\Desktop\scripts\minecraft.sp::Hook_EntitySound
L 04/23/2019 - 21:53:42: [SM] Exception reported: Invalid client index 533
L 04/23/2019 - 21:53:42: [SM] Blaming: minecraft.smx
L 04/23/2019 - 21:53:42: [SM] Call stack trace:
L 04/23/2019 - 21:53:42: [SM]   [0] GetClientEyeAngles
L 04/23/2019 - 21:53:42: [SM]   [1] Line 49, C:\Users\User\Desktop\scripts\minecraft.sp::Hook_EntitySound
L 04/23/2019 - 21:53:42: [SM] Exception reported: Invalid client index 536
L 04/23/2019 - 21:53:42: [SM] Blaming: minecraft.smx
L 04/23/2019 - 21:53:42: [SM] Call stack trace:
L 04/23/2019 - 21:53:42: [SM]   [0] GetClientEyeAngles
L 04/23/2019 - 21:53:42: [SM]   [1] Line 49, C:\Users\User\Desktop\scripts\minecraft.sp::Hook_EntitySound
L 04/23/2019 - 21:53:43: [SM] Exception reported: Invalid client index 533
L 04/23/2019 - 21:53:43: [SM] Blaming: minecraft.smx
L 04/23/2019 - 21:53:43: [SM] Call stack trace:
L 04/23/2019 - 21:53:43: [SM]   [0] GetClientEyeAngles
L 04/23/2019 - 21:53:43: [SM]   [1] Line 49, C:\Users\User\Desktop\scripts\minecraft.sp::Hook_EntitySound
L 04/23/2019 - 21:53:43: [SM] Exception reported: Invalid client index 536

and spam spam

**Comment by MoonlyDays** [comment]
Fixed within the latest commit

**Comment by zyox123cc** [comment]
thx and i make this https://imgur.com/bglaA41
Will wood doors be added in the future?
also shadow bug https://imgur.com/ed7DhUe

Sometimes the square will disappear inexplicably

**Comment by MoonlyDays** [comment]
Doors are something i cant make because player is unable to walk between two blocks. Player is to wide for them. This is fixable by making blocks larger. But in this case player won't be able to jump on the block. 
So, doors can be made but they will be useless.
